version: '3'
services:
  www:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/var/www/html"
      - "../responses:/var/www/responses"
    ports:
      - "80:80"
      - 443:443
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATEBASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - ./docker/db:/var/lib/mysql
    ports:
      - "${DB_PORT}:${DB_PORT}"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306